# Generated by Django 3.0.8 on 2020-08-09 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200809_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='count_correct_answers',
            new_name='count_correct_questions',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='count_answers',
            new_name='count_questions',
        ),
    ]
